import { WebVitals } from '@/components';
import { routing } from '@/i18n/routing';
import { Toaster } from '@repo/ui';
import type { Metadata } from 'next';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import { notFound } from 'next/navigation';
import { PropsWithChildren } from 'react';
import '../globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  params: Promise<{ locale: string }>;
}

export default async function RootLayout(
  props: PropsWithChildren<RootLayoutProps>,
) {
  const { children, params } = props;
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html
      lang={locale}
      data-scroll-behavior="smooth"
      className={`${inter.variable} scrollbar-thin scrollbar-thumb-border scrollbar-track-background`}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <Toaster theme="light" position="top-center" />
          {children}
        </NextIntlClientProvider>
        <WebVitals />
      </body>
    </html>
  );
}
